<?php
use App\Cliente;
use Illuminate\Database\Seeder;

class ClientesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	DB::table('clientes')->insert([
    		'id' => 1 ,
    		'nombre' => 'Cliente',
    		'direccion' =>"Av" ,
    		'email' => 'example@example.com',
    		'telefono' => "111-0000 " ,
    		'anexo' => "0",
    		'celular' => "9999999",
    		'empresa' => "J&P SAC" ,
    		'documento_identificacion' => 'RUC',
    		'numero_documento' => "20000000001",
    		'ciudad' => "Lima",
    		'departamento' => "Lima",
    		'pais' => "Peru",
    		'tipo_cliente' => "Cliente Frencuentes",
    		'cod_postal' => "7021",
    		'aniversario' => "0/00/0000 ",
    		'fecha_registro' => "2020-08-01 ",
    		'created_at' => '2020-08-01 11:36:57',
    		'updated_at' => "2020-08-01 11:36:58" ,
    	]);

    	// DB::table('clientes')->insert([
    	// 	'id' => 2 ,
    	// 	'nombre' => 'Perez Cardenas Jose',
    	// 	'direccion' =>"AV. La Capitania 190 - Huachipa" ,
    	// 	'email' => 'jose.perez@gloria.com.pe',
    	// 	'telefono' => "317-2500" ,
    	// 	'anexo' => "0",
    	// 	'celular' => "995605359",
    	// 	'empresa' => "GLORIA SAC" ,
    	// 	'documento_identificacion' => 'RUC',
    	// 	'numero_documento' => "20100190798",
    	// 	'ciudad' => "Lima",
    	// 	'departamento' => "Lima",
    	// 	'pais' => "Peru",
    	// 	'tipo_cliente' => "Cliente Frencuentes",
    	// 	'cod_postal' => "7021",
    	// 	'aniversario' => "0/00/0000",
    	// 	'fecha_registro' => "2020-08-01 ",
    	// 	'created_at' => '2020-08-01 11:36:57',
    	// 	'updated_at' => "2020-08-01 11:36:58" ,
    	// ]);

    	// DB::table('clientes')->insert([
    	// 	'id' => 3 ,
    	// 	'nombre' => 'Nelver Ponce Esquivel',
    	// 	'direccion' =>"AV. La Capitania 190 - Huachipa" ,
    	// 	'email' => 'nponce@gloria.com.pe',
    	// 	'telefono' => "317-2500 " ,
    	// 	'anexo' => "2109",
    	// 	'celular' => "988570896",
    	// 	'empresa' => "GLORIA SAC" ,
    	// 	'documento_identificacion' => 'RUC',
    	// 	'numero_documento' => "20100190799",
    	// 	'ciudad' => "Lima",
    	// 	'departamento' => "Lima",
    	// 	'pais' => "Peru",
    	// 	'tipo_cliente' => "Cliente Frencuentes",
    	// 	'cod_postal' => "7021",
    	// 	'aniversario' => "0/00/0000",
    	// 	'fecha_registro' => "2020-08-01",
    	// 	'created_at' => '2020-08-01 11:36:57',
    	// 	'updated_at' => "2020-08-01 11:36:58" ,
    	// ]);

    	// DB::table('clientes')->insert([
    	// 	'id' => 4 ,
    	// 	'nombre' => 'Arce Morante Jady',
    	// 	'direccion' =>"AV. La Capitania 190 - Huachipa" ,
    	// 	'email' => 'jmarce@gloria.com.pe',
    	// 	'telefono' => "317 2500 " ,
    	// 	'anexo' => "2126",
    	// 	'celular' => "971945358",
    	// 	'empresa' => "GLORIA SAC" ,
    	// 	'documento_identificacion' => 'RUC',
    	// 	'numero_documento' => "20100190800",
    	// 	'ciudad' => "Lima",
    	// 	'departamento' => "Lima",
    	// 	'pais' => "Peru",
    	// 	'tipo_cliente' => "Cliente Frencuentes",
    	// 	'cod_postal' => "7021",
    	// 	'aniversario' => "0/00/0000",
    	// 	'fecha_registro' => "2020-08-01",
    	// 	'created_at' => '2020-08-01 11:36:57',
    	// 	'updated_at' => "2020-08-01 11:36:58" ,
    	// ]);

    	// DB::table('clientes')->insert([
    	// 	'id' => 5 ,
    	// 	'nombre' => 'Victor Vasquez Cordova',
    	// 	'direccion' =>"AV. Republica de colombia N 791 San Isidro." ,
    	// 	'email' => 'vvasquez@lincuna.com.pe',
    	// 	'telefono' => "207-0080 " ,
    	// 	'anexo' => "7252",
    	// 	'celular' => "994610213",
    	// 	'empresa' => "CIA. MINERA LINCUNA S.A." ,
    	// 	'documento_identificacion' => 'RUC',
    	// 	'numero_documento' => "20458538701",
    	// 	'ciudad' => "Lima",
    	// 	'departamento' => "Lima",
    	// 	'pais' => "Peru",
    	// 	'tipo_cliente' => "Cliente Frencuentes",
    	// 	'cod_postal' => "7021",
    	// 	'aniversario' => "0/00/0000",
    	// 	'fecha_registro' => "2020-08-01",
    	// 	'created_at' => '2020-08-01 11:36:57',
    	// 	'updated_at' => "2020-08-01 11:36:58" ,
    	// ]);

    	// DB::table('clientes')->insert([
    	// 	'id' => 6 ,
    	// 	'nombre' => 'Magaly Cruz L.',
    	// 	'direccion' =>"Av. Republica de Argentina N 2577 Cercado de Lima." ,
    	// 	'email' => 'magaly.cruz.crubher@gmail.com',
    	// 	'telefono' => "562-2020 " ,
    	// 	'anexo' => "1941",
    	// 	'celular' => "0",
    	// 	'empresa' => "GEODRILL S.A.C." ,
    	// 	'documento_identificacion' => 'RUC',
    	// 	'numero_documento' => "20273877569",
    	// 	'ciudad' => "Lima",
    	// 	'departamento' => "Lima",
    	// 	'pais' => "Peru",
    	// 	'tipo_cliente' => "Cliente Frencuentes",
    	// 	'cod_postal' => "7021",
    	// 	'aniversario' => "0/00/0000",
    	// 	'fecha_registro' => "2020-08-01",
    	// 	'created_at' => '2020-08-01 11:36:57',
    	// 	'updated_at' => "2020-08-01 11:36:58" ,
    	// ]);

    	// DB::table('clientes')->insert([
    	// 	'id' => 7 ,
    	// 	'nombre' => 'Sadin Valdivia Huamantinco',
    	// 	'direccion' =>"Calle Las Begonias 415- San Isidro- Lima-Peru" ,
    	// 	'email' => 'sadin.valdivia@buenaventura.pe',
    	// 	'telefono' => "419 2500 " ,
    	// 	'anexo' => "5607",
    	// 	'celular' => "945909237",
    	// 	'empresa' => "PROCESADORA INDUSTRIAL RIO SECO S.A" ,
    	// 	'documento_identificacion' => 'DNI',
    	// 	'numero_documento' => "09505144",
    	// 	'ciudad' => "Lima",
    	// 	'departamento' => "Lima",
    	// 	'pais' => "Peru",
    	// 	'tipo_cliente' => "Cliente Frencuentes",
    	// 	'cod_postal' => "7021",
    	// 	'aniversario' => "0/00/0000",
    	// 	'fecha_registro' => "2020-08-01",
    	// 	'created_at' => '2020-08-01 11:36:57',
    	// 	'updated_at' => "2020-08-01 11:36:58" ,
    	// ]);

    	// DB::table('clientes')->insert([
    	// 	'id' => 8 ,
    	// 	'nombre' => 'Basti Crocco Parra',
    	// 	'direccion' =>"SUB LOTE 2C - CAJAMARQUILLA LURIGANCHO - CHOSICA LIMA" ,
    	// 	'email' => 'bcrocco@cementosinka.com.pe',
    	// 	'telefono' => "500-0600" ,
    	// 	'anexo' => "126",
    	// 	'celular' => "977712387",
    	// 	'empresa' => "CALIZA CEMENTO INCA S.A." ,
    	// 	'documento_identificacion' => 'DNI',
    	// 	'numero_documento' => "09505188",
    	// 	'ciudad' => "Lima",
    	// 	'departamento' => "Lima",
    	// 	'pais' => "Peru",
    	// 	'tipo_cliente' => "Cliente Frencuentes",
    	// 	'cod_postal' => "7021",
    	// 	'aniversario' => "0/00/0000",
    	// 	'fecha_registro' => "2020-08-01",
    	// 	'created_at' => '2020-08-01 11:36:57',
    	// 	'updated_at' => "2020-08-01 11:36:58" ,
    	// ]);

    	// DB::table('clientes')->insert([
    	// 	'id' => 9 ,
    	// 	'nombre' => 'Leslie Panta Bustinza',
    	// 	'direccion' =>"PJ. PERICLES NRO. 184 URB. BENJAMIN DOIG LOSSIO ROV. CONST. DEL CALLAO " ,
    	// 	'email' => 'contabilidad@gestemindperu.com',
    	// 	'telefono' => "51- 01-6477133" ,
    	// 	'anexo' => "0",
    	// 	'celular' => "986279258",
    	// 	'empresa' => "Gestion Tecnica Minera e Industrial Peru S.A.C" ,
    	// 	'documento_identificacion' => 'DNI',
    	// 	'numero_documento' => "01005144",
    	// 	'ciudad' => "Lima",
    	// 	'departamento' => "Lima",
    	// 	'pais' => "Peru",
    	// 	'tipo_cliente' => "Cliente Frencuentes",
    	// 	'cod_postal' => "7021",
    	// 	'aniversario' => "0/00/0000",
    	// 	'fecha_registro' => "2020-08-01",
    	// 	'created_at' => '2020-08-01 11:36:57',
    	// 	'updated_at' => "2020-08-01 11:36:58" ,
    	// ]);

    	// DB::table('clientes')->insert([
    	// 	'id' => 10 ,
    	// 	'nombre' => 'Carlos Bautista Sandoval',
    	// 	'direccion' =>"Av. Javier Prado Este 6519 - Urb. Pablo Canepa - La Molina" ,
    	// 	'email' => 'adm@promotoralastorres.com',
    	// 	'telefono' => "708-0700" ,
    	// 	'anexo' => "405",
    	// 	'celular' => "994187931",
    	// 	'empresa' => "Grifos Espinoza S.A." ,
    	// 	'documento_identificacion' => 'RUC',
    	// 	'numero_documento' => "20100111838",
    	// 	'ciudad' => "Lima",
    	// 	'departamento' => "Lima",
    	// 	'pais' => "Peru",
    	// 	'tipo_cliente' => "Cliente Frencuentes",
    	// 	'cod_postal' => "7021",
    	// 	'aniversario' => "0/00/0000",
    	// 	'fecha_registro' => "2020-08-01",
    	// 	'created_at' => '2020-08-01 11:36:57',
    	// 	'updated_at' => "2020-08-01 11:36:58" ,
    	// ]);

    	// DB::table('clientes')->insert([
    	// 	'id' => 11 ,
    	// 	'nombre' => 'Roger Silva Carrasco',
    	// 	'direccion' =>"Av. Javier Prado Este N 4109 Santiago de Surco-Lima" ,
    	// 	'email' => 'rsilva@casacontratistas.com',
    	// 	'telefono' => "0" ,
    	// 	'anexo' => "0",
    	// 	'celular' => "985084430",
    	// 	'empresa' => "Construccion y Administracion S.A." ,
    	// 	'documento_identificacion' => 'RUC',
    	// 	'numero_documento' => "20109565017",
    	// 	'ciudad' => "Lima",
    	// 	'departamento' => "Lima",
    	// 	'pais' => "Peru",
    	// 	'tipo_cliente' => "Cliente Frencuentes",
    	// 	'cod_postal' => "7021",
    	// 	'aniversario' => "0/00/0000",
    	// 	'fecha_registro' => "2020-08-01",
    	// 	'created_at' => '2020-08-01 11:36:57',
    	// 	'updated_at' => "2020-08-01 11:36:58" ,
    	// ]);
    }
}
